#pragma once

#define MINIX3_MAGIC 0x4d5a
#define MINIX3_SUPERBLOCK_OFFSET 1024
#define MINIX3_IZONE_START_BLOCK 2
#define MINIX3_DEFAULT_BLOCK_SIZE 1024
#define MINIX3_INODE_SIZE 64
#define MINIX3_DIR_NAME_MAX 60
#define MINIX3_ZONES_PER_INODE 10
#define MINIX3_DIRECT_ZONES 7
#define MINIX3_SINGLE_INDIRECT_ZONE_INDEX MINIX3_DIRECT_ZONES
#define MINIX3_SINGLE_INDIRECT_ZONE_INDEX_COUNT 1
#define MINIX3_DOUBLE_INDIRECT_ZONE_INDEX (MINIX3_DIRECT_ZONES + 1)
#define MINIX3_DOUBLE_INDIRECT_ZONE_INDEX_COUNT 1
#define MINIX3_TRIPLE_INDIRECT_ZONE_INDEX (MINIX3_DIRECT_ZONES + 2)
#define MINIX3_TRIPLE_INDIRECT_ZONE_INDEX_COUNT 1