#pragma once

enum ErrorCode
{
	SUCCESS = 0,
	ERROR_OPEN_DEVICE_FAIL = 1,
	ERROR_CLOSE_DEVICE_FAIL = 2,
	ERROR_READ_FAIL = 3,
	ERROR_WRITE_FAIL = 4,
	ERROR_INVALID_SUPERBLOCK = 5,
	ERROR_CANNOT_ALLOCATE_MEMORY = 6,
	ERROR_FS_BROKEN = 7,
};