#pragma once

enum ErrorCode
{
	SUCCESS = 0,
	ERROR_OPEN_DEVICE_FAIL = 1,
	ERROR_CLOSE_DEVICE_FAIL = 2,
	ERROR_READ_FAIL = 3,
	ERROR_WRITE_FAIL = 4,
	ERROR_INVALID_SUPERBLOCK = 5,
	ERROR_CANNOT_ALLOCATE_MEMORY = 6,
	ERROR_FS_BROKEN = 7,
	ERROR_FILE_NOT_FOUND = 8,
	ERROR_NOT_REGULAR_FILE = 9,
	ERROR_NOT_DIRECTORY = 10,
	ERROR_INVALID_INODE_NUMBER = 11,
	ERROR_CANNOT_ALLOCATE_BMAP = 12,
	ERROR_FREEING_UNALLOCATED_BMAP = 13,
	ERROR_INVALID_BMAP_INDEX = 14,
};